apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-nestjs-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: sample.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sample-nestjs-service
              port:
                number: 3000
